name: publish docker image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '44 12 * * *'
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  ORGANIZATION: ArchitectureGroup

jobs:
  run-dotnet-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Skoruba.IdentityServer4.Admin.sln
    - name: Build
      run: dotnet build --no-restore Skoruba.IdentityServer4.Admin.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Skoruba.IdentityServer4.Admin.sln

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: run-dotnet-build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.9
        
      - name: Checkout repository
        uses: actions/checkout@v2
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/BCLS-IdentityServer4-Admin

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image Skoruba.IdentityServer4.Admin
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Skoruba.IdentityServer4.Admin/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ env.REGISTRY }}/architecturegroup/bcls-identityserver4-admin:${{ steps.branch-name.outputs.current_branch }}"
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Build and push Docker image Skoruba.IdentityServer4.Admin.Api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Skoruba.IdentityServer4.Admin.Api/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ env.REGISTRY }}/architecturegroup/bcls-identityserver4-admin-api:${{ steps.branch-name.outputs.current_branch }}"
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Build and push Docker image Skoruba.IdentityServer4.STS.Identity
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Skoruba.IdentityServer4.STS.Identity/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ env.REGISTRY }}/architecturegroup/bcls-identityserver4-sts-identity:${{ steps.branch-name.outputs.current_branch }}"
          labels: ${{ steps.meta.outputs.labels }}

